/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs.client;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Client client = new Client();
        while(true){
         client.getMessages();
        }
    }
}
